# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"
set -g automatic-rename off
set -g allow-rename off

# Catppuccin Mocha
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status on
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#[fg=#{?client_prefix,#{@thm_red},#{@thm_green}},bg=default]#[fg=#{@thm_crust},bg=#{?client_prefix,#{@thm_red},#{@thm_green}}] #[fg=#{@thm_fg},bg=#{@thm_surface_0}] #S #[fg=#{@thm_surface_0},bg=default] "
set -g status-right "#{E:@catppuccin_status_directory}"
# set -agF status-right "#{E:@catppuccin_status_load}"
set -agF status-right "#{E:@catppuccin_status_date_time}"

# Which-key style tmux command menu
run-shell ~/.config/tmux/plugins/tmux-which-key/plugin.sh.tmux
